# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gnss.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import header_pb2 as header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='gnss.proto',
  package='phoenix.msg.localization',
  syntax='proto2',
  serialized_pb=_b('\n\ngnss.proto\x12\x18phoenix.msg.localization\x1a\x0cheader.proto\"\xb2\x06\n\x04Gnss\x12*\n\x06header\x18\x01 \x01(\x0b\x32\x1a.phoenix.msg.common.Header\x12\x13\n\x08latitude\x18\x02 \x01(\x01:\x01\x30\x12\x14\n\tlongitude\x18\x03 \x01(\x01:\x01\x30\x12\x13\n\x08\x61ltitude\x18\x04 \x01(\x01:\x01\x30\x12\x17\n\x0cheading_gnss\x18\x05 \x01(\x02:\x01\x30\x12\x10\n\x05x_utm\x18\x06 \x01(\x01:\x01\x30\x12\x10\n\x05y_utm\x18\x07 \x01(\x01:\x01\x30\x12\x10\n\x05z_utm\x18\x08 \x01(\x01:\x01\x30\x12\x16\n\x0bheading_utm\x18\t \x01(\x02:\x01\x30\x12\x11\n\x06x_odom\x18\n \x01(\x01:\x01\x30\x12\x11\n\x06y_odom\x18\x0b \x01(\x01:\x01\x30\x12\x11\n\x06z_odom\x18\x0c \x01(\x01:\x01\x30\x12\x17\n\x0cheading_odom\x18\r \x01(\x02:\x01\x30\x12\x10\n\x05pitch\x18\x0e \x01(\x02:\x01\x30\x12\x0f\n\x04roll\x18\x0f \x01(\x02:\x01\x30\x12\x0e\n\x03v_e\x18\x10 \x01(\x02:\x01\x30\x12\x0e\n\x03v_n\x18\x11 \x01(\x02:\x01\x30\x12\x0e\n\x03v_u\x18\x12 \x01(\x02:\x01\x30\x12\x12\n\x07v_x_utm\x18\x13 \x01(\x02:\x01\x30\x12\x12\n\x07v_y_utm\x18\x14 \x01(\x02:\x01\x30\x12\x12\n\x07v_z_utm\x18\x15 \x01(\x02:\x01\x30\x12\x13\n\x08v_x_odom\x18\x16 \x01(\x02:\x01\x30\x12\x13\n\x08v_y_odom\x18\x17 \x01(\x02:\x01\x30\x12\x13\n\x08v_z_odom\x18\x18 \x01(\x02:\x01\x30\x12J\n\x0bgnss_status\x18\x19 \x01(\x0e\x32%.phoenix.msg.localization.Gnss.Status:\x0eSTATUS_INVALID\x12I\n\nutm_status\x18\x1a \x01(\x0e\x32%.phoenix.msg.localization.Gnss.Status:\x0eSTATUS_INVALID\x12J\n\x0bodom_status\x18\x1b \x01(\x0e\x32%.phoenix.msg.localization.Gnss.Status:\x0eSTATUS_INVALID\"T\n\x06Status\x12\x12\n\x0eSTATUS_INVALID\x10\x00\x12\x0e\n\nSTATUS_BAD\x10\x01\x12\x15\n\x11STATUS_CONVERGING\x10\x02\x12\x0f\n\x0bSTATUS_GOOD\x10\x03')
  ,
  dependencies=[header__pb2.DESCRIPTOR,])



_GNSS_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='phoenix.msg.localization.Gnss.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STATUS_INVALID', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_BAD', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_CONVERGING', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_GOOD', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=789,
  serialized_end=873,
)
_sym_db.RegisterEnumDescriptor(_GNSS_STATUS)


_GNSS = _descriptor.Descriptor(
  name='Gnss',
  full_name='phoenix.msg.localization.Gnss',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='phoenix.msg.localization.Gnss.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='phoenix.msg.localization.Gnss.latitude', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='phoenix.msg.localization.Gnss.longitude', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='altitude', full_name='phoenix.msg.localization.Gnss.altitude', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='heading_gnss', full_name='phoenix.msg.localization.Gnss.heading_gnss', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x_utm', full_name='phoenix.msg.localization.Gnss.x_utm', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y_utm', full_name='phoenix.msg.localization.Gnss.y_utm', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z_utm', full_name='phoenix.msg.localization.Gnss.z_utm', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='heading_utm', full_name='phoenix.msg.localization.Gnss.heading_utm', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x_odom', full_name='phoenix.msg.localization.Gnss.x_odom', index=9,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y_odom', full_name='phoenix.msg.localization.Gnss.y_odom', index=10,
      number=11, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z_odom', full_name='phoenix.msg.localization.Gnss.z_odom', index=11,
      number=12, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='heading_odom', full_name='phoenix.msg.localization.Gnss.heading_odom', index=12,
      number=13, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pitch', full_name='phoenix.msg.localization.Gnss.pitch', index=13,
      number=14, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='roll', full_name='phoenix.msg.localization.Gnss.roll', index=14,
      number=15, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='v_e', full_name='phoenix.msg.localization.Gnss.v_e', index=15,
      number=16, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='v_n', full_name='phoenix.msg.localization.Gnss.v_n', index=16,
      number=17, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='v_u', full_name='phoenix.msg.localization.Gnss.v_u', index=17,
      number=18, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='v_x_utm', full_name='phoenix.msg.localization.Gnss.v_x_utm', index=18,
      number=19, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='v_y_utm', full_name='phoenix.msg.localization.Gnss.v_y_utm', index=19,
      number=20, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='v_z_utm', full_name='phoenix.msg.localization.Gnss.v_z_utm', index=20,
      number=21, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='v_x_odom', full_name='phoenix.msg.localization.Gnss.v_x_odom', index=21,
      number=22, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='v_y_odom', full_name='phoenix.msg.localization.Gnss.v_y_odom', index=22,
      number=23, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='v_z_odom', full_name='phoenix.msg.localization.Gnss.v_z_odom', index=23,
      number=24, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gnss_status', full_name='phoenix.msg.localization.Gnss.gnss_status', index=24,
      number=25, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='utm_status', full_name='phoenix.msg.localization.Gnss.utm_status', index=25,
      number=26, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='odom_status', full_name='phoenix.msg.localization.Gnss.odom_status', index=26,
      number=27, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _GNSS_STATUS,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=873,
)

_GNSS.fields_by_name['header'].message_type = header__pb2._HEADER
_GNSS.fields_by_name['gnss_status'].enum_type = _GNSS_STATUS
_GNSS.fields_by_name['utm_status'].enum_type = _GNSS_STATUS
_GNSS.fields_by_name['odom_status'].enum_type = _GNSS_STATUS
_GNSS_STATUS.containing_type = _GNSS
DESCRIPTOR.message_types_by_name['Gnss'] = _GNSS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Gnss = _reflection.GeneratedProtocolMessageType('Gnss', (_message.Message,), dict(
  DESCRIPTOR = _GNSS,
  __module__ = 'gnss_pb2'
  # @@protoc_insertion_point(class_scope:phoenix.msg.localization.Gnss)
  ))
_sym_db.RegisterMessage(Gnss)


# @@protoc_insertion_point(module_scope)
